name: apvi
favicon: null
layout_spectrum: 0
typography_spectrum: 0.28795
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1e1d'
    - '#685e53'
    - '#f3f8f6'
    - '#8d887d'
    - '#65c9fc'
  brandStrength: 0
  lightness: 0.125
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
