favicon: null
name: apvi
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.4924115
  lightness: 0.5067453
  brandStrength: 0
  brandColors:
    - '#1f1e1d'
    - '#685e53'
    - '#f3f8f6'
    - '#8d887d'
    - '#65c9fc'
  rhythmicContrast: 0.3296796
typography_spectrum: 0.5370995
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
layout_spectrum: 0.148398
