name: apvi
favicon: null
layout_spectrum: 0.9526967962738127
typography_spectrum: 0.5580944372341037
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2480372276622802
  lightness: 0.4373410453554243
  saturation: 0.43960317270830274
  rhythmicContrast: 0.7583156435284764
purpose: []
